
          - name: Build PlatformIO Project for Linux
            run: pio run -e linux

          - name: Move files into artifact directory
            shell: bash
            run: |
              mkdir build
              cp -r .pio/build/linux/program build
              cp -r storage build

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: linux-build
              include-hidden-files: true
              path: |
                build/

    macos_build_test_upload:
        runs-on: macos-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: |
                  ~/.cache/pip
                  ~/.platformio/.cache
                  .pio/build_cache
                  .pio/libdeps
                key: ${{ runner.os }}-platformio-ci-macos

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install PlatformIO Core
              run: pip install --upgrade platformio

            - name: Install SDL2
              run: brew install SDL2

            - name: Run tests for macOS
              run: DYLD_LIBRARY_PATH="`brew --prefix sdl2`/lib" pio test -e macos --json-output-path macos-test-report.json --junit-output-path macos-test-report.xml

            - name: Upload test reports
              if: success() || failure()
              uses: actions/upload-artifact@v4
              with:
                name: macos-test-reports
                path: |
                  macos-test-report.json
                  macos-test-report.xml

            - name: Build PlatformIO Project for macOS
              run: DYLD_LIBRARY_PATH="`brew --prefix sdl2`/lib" pio run -e macos

            - name: Move files into artifact directory
              shell: bash
              run: |
                mkdir build
                cp -r .pio/build/macos/program build
                cp -r storage build
                chmod +x build/program

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: macos-build
                include-hidden-files: true
                path: |
                  build/

    windows_build_test_upload:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: |
                  ~/.cache/pip
                  ~/.platformio/.cache
                  .pio/build_cache
                  .pio/libdeps
                key: ${{ runner.os }}-platformio-ci-windows

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install PlatformIO Core
              run: pip install --upgrade platformio

            - name: Run tests for Windows
              run: pio test -e windows --json-output-path windows-test-report.json --junit-output-path windows-test-report.xml

            - name: Upload test reports
              if: success() || failure()
              uses: actions/upload-artifact@v4
              with:
                name: windows-test-reports
                path: |
                  windows-test-report.json
                  windows-test-report.xml

            - name: Build PlatformIO Project for Windows
              run: pio run -e windows

            - name: Move files into artifact directory
              shell: bash
              run: |
                mkdir build
                cp -r .pio/build/windows/program.exe build
                cp -r .pio/build/windows/*.dll build
                cp -r storage build

            - name: Copy required DLLs into artifact directory
              run: python scripts/github_actions/windows/get_dll.py build

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: windows-build
                include-hidden-files: true
                path: |
                  build/
